### Data Analysis

In [42]:
import pandas as pd

In [43]:
#Importing the CSV processed v1
path_from= '/home/usuario/Documentos/Ironhack/Project_1_0420_JuanMunoz/data/processed'

#%difference w/out finisher
df_all = pd.read_csv(f'{path_from}/df_all.csv', sep=';') 

df_all[400:415]

,uuid,education_level,full_time_job,job_code,job_title,country_code,country,rural,age,gender,has_children,age_group,quest_awareness,quest_vote,quest_effect,quest_arguments_for,quest_arguments_against
400,6bd1b9d0-d8cc-0133-618d-0a81e8b09a82,low,no,Unemployed,Unemployed,BG,Bulgaria,urban,18,male,no,14_25,I have heard just a little about it,I would not vote,work less,It reduces anxiety about financing basic needs...,Foreigners might come to my country and take a...
401,c85eefa0-db3d-0133-8bc5-0a81e8b09a82,high,yes,e55556364d2096578fd153e9800e826f,Database Consultant,BG,Bulgaria,city,53,female,yes,40_65,I have heard just a little about it,I would probably vote for it,work less,It encourages financial independence and self-...,It might encourage people to stop working | Fo...
402,a4b03050-da50-0133-3639-0a81e8b09a82,high,yes,c1b670eba9ccb65e7c99f7da116d5b9c,Database Architect,BG,Bulgaria,urban,56,male,yes,40_65,I know something about it,I would vote for it,work as a freelancer,It encourages financial independence and self-...,It might encourage people to stop working | It...
403,41e17d40-da5e-0133-67a5-0a81e8b09a82,medium,yes,2173ff3afd8d28192f7cf119af201940,Data Modeling Specialist,BG,Bulgaria,urban,48,female,yes,40_65,I have never heard of it,I would vote for it,spend more time with my family,It reduces anxiety about financing basic needs,It might encourage people to stop working | Fo...
404,e6497150-da0f-0133-feb5-0a81e8b09a82,medium,yes,a2a9fbe67b4aa2b551ba0f3adac90a99,"Engineer, System Electronic Data Processing (E...",BG,Bulgaria,city,40,female,yes,40_65,I know something about it,I would not vote,None of the above,It creates more equality of opportunity,Only the people who need it most should get so...
405,04852950-d9d4-0133-cf28-0a81e8b09a82,high,yes,e7b3e1c6a32c7247cd4857e4c3574165,Data Processing Systems Analyst,BG,Bulgaria,city,49,male,yes,40_65,I know something about it,I would probably vote against it,work as a freelancer,None of the above,It might encourage people to stop working | Fo...
406,8407ff70-da31-0133-af53-0a81e8b09a82,high,yes,a2a9fbe67b4aa2b551ba0f3adac90a99,"Engineer, System Electronic Data Processing (E...",BG,Bulgaria,urban,29,female,no,26_39,I know something about it,I would not vote,gain additional skills,"It increases solidarity, because it is funded ...",It increases dependence on the state
407,20048ad0-d959-0133-5bc2-0a81e8b09a82,high,no,Unemployed,Unemployed,BG,Bulgaria,urban,52,male,yes,40_65,I know something about it,I would vote for it,gain additional skills,It reduces anxiety about financing basic needs...,Only the people who need it most should get so...
408,4724f180-da26-0133-6985-0a81e8b09a82,undefined,no,Unemployed,Unemployed,BG,Bulgaria,urban,41,male,yes,40_65,I have never heard of it,I would vote for it,spend more time with my family,It encourages financial independence and self-...,It might encourage people to stop working
409,7978a9b0-d98e-0133-f1cb-0a81e8b09a82,high,no,Unemployed,Unemployed,BG,Bulgaria,urban,52,male,yes,40_65,I have heard just a little about it,I would probably vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs,It might encourage people to stop working | Fo...
410,b5e405c0-daf1-0133-433e-0a81e8b09a82,medium,yes,f5bc91b67dc30ad204158092116c4ed2,Clinical Data Manager,BG,Bulgaria,non-rural,40,male,no,40_65,I know something about it,I would probably vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs,Only the people who need it most should get so...
411,873b5910-da42-0133-6024-0a81e8b09a82,high,yes,970eb38c7b3eb080466052ea994af189,Internet Database Specialist,BG,Bulgaria,non-rural,45,male,yes,40_65,I have heard just a little about it,I would probably vote for it,gain additional skills,It creates more equality of opportunity | It r...,It might encourage people to stop working | It...
412,cb8499d0-d9a2-0133-adac-0a81e8b09a82,high,yes,a003702c0cea282e17967772dd83de5e,Data Security Analyst,BG,Bulgaria,non-rural,23,female,no,14_25,I have never heard of it,I would vote for it,gain additional skills,It encourages financial independence and self-...,It is impossible to finance | It might encoura...
413,a2779100-da33-0133-ab51-0a81e8b09a82,medium,no,Unemployed,Unemployed,BG,Bulgaria,urban,17,female,no,14_25,I have never heard of it,I would vote for it,A basic income would not affect my work choices,It reduces anxiety about financing basic needs,It might encourage people to stop working
414,f5cc6eb0-d9a8-0133-0d2a-0a81e8b09a82,medium,yes,781f5d3a80812531fdc81125a527a626,Data Warehouse Specialist,BG,Bulgaria,urban,39,male,yes,26_39,I know something about it,I would probably vote against it,A basic income would not affect my work choices,It creates more equality of opportunity,It might encourage people to stop working

# Challenge 1

In [40]:
Country	Job Title	Age (1)	Quantity	Percentage

SyntaxError: invalid syntax (<ipython-input-40-7bd30c87a723>, line 1)

In [70]:
df_result = df_all.groupby(['country','job_title','age'])['uuid'].agg(['count']).sort_values(by='count',ascending = False)


#df_result = df_result[df_result['job_title'] == 'Data Scientist']
display(df_result)

                                                                    count
country        job_title                                       age
United Kingdom Unemployed                                      43      27
Germany        Unemployed                                      19      27
                                                               17      26
                                                               18      26
France         Unemployed                                      20      25
...                                                                   ...
Germany        Head of Information Systems and Data Processing 48       1
                                                               46       1
                                                               45       1
                                                               34       1
Italy          Database Analyst                                37       1

[6141 rows x 1 columns]

# quest_arguments_against Analysis

In [16]:
#function for analysis of arguments for:
def replace_comma(x):
    try:
        return x.replace(" ", "").replace(",", "-").lower()
    except:
        return x 

#creating a new column in the dataset    
df_all['quest_arguments_against_2'] = df_all['quest_arguments_against'].apply(replace_comma)

#function that shows the real unique values of the column dataframe
def list_unique(x):
    
    value_list = []
    for i in df_all[x]:
        value = i.split("|")
        value_list.append(value) 

    final_list = []
    for i in value_list:
        for j in i:
            final_list.append(j)
    return final_list

def remove_duplicates(x):
    return list(dict.fromkeys(x))

fin_list = list_unique('quest_arguments_against_2')
final_list = remove_duplicates(fin_list)

print (final_list)
len(final_list)


#Updates the new column as a list of responses
df_all['quest_arguments_against_2'] 
df_all['quest_arguments_against_2'] = df_all['quest_arguments_against_2'].str.replace("|",",")


value_list = []
for i in df_all['quest_arguments_against_2']:
    val = list(i.split(","))
    value_list.append(val)
     
df_all['quest_arguments_against_2'] = value_list

['noneoftheabove', 'itmightencouragepeopletostopworking', 'foreignersmightcometomycountryandtakeadvantageofthebenefit', 'itisimpossibletofinance', 'itincreasesdependenceonthestate', 'itisagainsttheprincipleoflinkingmeritandreward', 'onlythepeoplewhoneeditmostshouldgetsomethingfromthestate']

In [25]:
# count the times we have each answer in total
a= 0
b= 0
c= 0
d= 0
e= 0
f= 0
g= 0

for data in df_all['quest_arguments_against_2']:
    if len(list(data))==1:
        if data[0] == 'noneoftheabove':
            a += 1
        elif data[0] == 'itmightencouragepeopletostopworking':
            b += 1
        elif data[0] == 'foreignersmightcometomycountryandtakeadvantageofthebenefit':
            c += 1
        elif data[0] == 'itisimpossibletofinance':
            d += 1
        elif data[0] == 'itincreasesdependenceonthestate':
            e += 1
        elif data[0] == 'itisagainsttheprincipleoflinkingmeritandreward':
            f += 1
        elif data[0] == 'onlythepeoplewhoneeditmostshouldgetsomethingfromthestate':
            g += 1
    else:
        for datain in list(data):
            if datain == 'noneoftheabove':
                a += 1
            elif datain == 'itmightencouragepeopletostopworking':
                b += 1
            elif datain == 'foreignersmightcometomycountryandtakeadvantageofthebenefit':
                c += 1
            elif datain == 'itisimpossibletofinance':
                d += 1
            elif datain == 'itincreasesdependenceonthestate':
                e += 1
            elif datain == 'itisagainsttheprincipleoflinkingmeritandreward':
                f += 1
            elif datain == 'onlythepeoplewhoneeditmostshouldgetsomethingfromthestate':
                g += 1      

dict_result = {'None of the above':a,
'It might encourage people to stop working':b,
'Foreigners might come to my country and take advantage of the benefit':c, 
'It is impossible to finance':d,
'It increases dependence on the state':e,
'It is against the principle of linking merit and reward':f,
'Only the people who need it most should get something from the state':g}

df_answer_against = pd.DataFrame.from_dict(dict_result, orient='index',columns = ['Answers'])


df_answer_against['%Total'] = round((df_answer_against['Answers']/len(df_all['quest_arguments_against_2'])*100),2).astype(str) + '%'

df_answer_against = df_answer_against.sort_values('Answers', ascending=False)

# quest_arguments_for Analysis

In [ ]:
#function for analysis of arguments for:
def replace_comma(x):
    try:
        return x.replace(" ", "").replace(",", "-").lower()
    except:
        return x 

#creating a new column in the dataset    
df_all['quest_arguments_for_2'] = df_all['quest_arguments_for'].apply(replace_comma)

#function that shows the real unique values of the column dataframe
def list_unique(x):
    
    value_list = []
    for i in df_all[x]:
        value = i.split("|")
        value_list.append(value) 

    final_list = []
    for i in value_list:
        for j in i:
            final_list.append(j)
    return final_list

def remove_duplicates(x):
    return list(dict.fromkeys(x))

fin_list = list_unique('quest_arguments_for_2')
final_list = remove_duplicates(fin_list)

print (final_list)
len(final_list)


#Updates the new column as a list of responses
df_all['quest_arguments_for_2'] 
df_all['quest_arguments_for_2'] = df_all['quest_arguments_for_2'].str.replace("|",",")


value_list = []
for i in df_all['quest_arguments_for_2']:
    val = list(i.split(","))
    value_list.append(val)
     
df_all['quest_arguments_for_2'] = value_list

In [23]:
# count the times we have each answer in total
a= 0
b= 0
c= 0
d= 0
e= 0
f= 0
g= 0

for data in df_all['quest_arguments_for_2']:
    if len(list(data))==1:
        if data[0] == 'noneoftheabove':
            a += 1
        elif data[0] == 'itincreasesappreciationforhouseholdworkandvolunteering':
            b += 1
        elif data[0] == 'itencouragesfinancialindependenceandself-responsibility':
            c += 1
        elif data[0] == 'itreducesanxietyaboutfinancingbasicneeds':
            d += 1
        elif data[0] == 'itcreatesmoreequalityofopportunity':
            e += 1
        elif data[0] == 'itreducesbureaucracyandadministrativeexpenses':
            f += 1
        elif data[0] == 'itincreasessolidarity-becauseitisfundedbyeveryone':
            g += 1
    else:
        for datain in list(data):
            if datain == 'noneoftheabove':
                a += 1
            elif datain == 'itincreasesappreciationforhouseholdworkandvolunteering':
                b += 1
            elif datain == 'itencouragesfinancialindependenceandself-responsibility':
                c += 1
            elif datain == 'itreducesanxietyaboutfinancingbasicneeds':
                d += 1
            elif datain == 'itcreatesmoreequalityofopportunity':
                e += 1
            elif datain == 'itreducesbureaucracyandadministrativeexpenses':
                f += 1
            elif datain == 'itincreasessolidarity-becauseitisfundedbyeveryone':
                g += 1      

dict_result = {'None of the above':a,
'It increases appreciation for household work and volunteering':b,
'It encourages financial independence and self-responsibility':c, 
'It reduces anxiety about financing basic needs':d,
'It creates more equality of opportunity':e,
'It reduces bureaucracy and administrative expenses':f,
'It increase ssolidarity because it is funded by everyone':g}

df_answer_for = pd.DataFrame.from_dict(dict_result, orient='index',columns = ['Answers'])


df_answer_for['%Total'] = round((df_answer_for['Answers']/len(df_all['quest_arguments_for_2'])*100),2).astype(str) + '%'

df_answer_for = df_answer_for.sort_values('Answers', ascending=False)

# Bonus 1

In [27]:
display(df_answer_for)
display(df_answer_against)

                                                    Answers  %Total
It reduces anxiety about financing basic needs         3893  40.35%
It creates more equality of opportunity                2955  30.62%
None of the above                                      2163  22.42%
It encourages financial independence and self-r...     2148  22.26%
It increase ssolidarity because it is funded by...     2052  21.27%
It increases appreciation for household work an...     2013  20.86%
It reduces bureaucracy and administrative expenses     1510  15.65%

                                                    Answers  %Total
It might encourage people to stop working              4232  43.86%
Foreigners might come to my country and take ad...     3341  34.63%
It is impossible to finance                            3218  33.35%
Only the people who need it most should get som...     3107   32.2%
It increases dependence on the state                   2394  24.81%
It is against the principle of linking merit an...     2082  21.58%
None of the above                                      1381  14.31%

In [64]:
#Export the detail analysis result to a CSV
path_to= '/home/usuario/Documentos/Ironhack/Project_1_0420_JuanMunoz/data/results'
df_result.to_csv(f'{path_to}/df_result.csv',index = False, header=True, sep = ';')
df_answer_for.to_csv(f'{path_to}/df_answer_for.csv',index = False, header=True, sep = ';')
df_answer_against.to_csv(f'{path_to}/df_answer_against.csv',index = False, header=True, sep = ';')