### Data Wrangling

In [1]:
import pandas as pd
from datetime import date

In [2]:
#Importing the CSV processed v1
path_from= '/home/usuario/Documentos/Ironhack/Project_1_0420_JuanMunoz/data/processed'

#%difference w/out finisher
df_all = pd.read_csv(f'{path_from}/raw_data_project_all.csv', sep=';') 

df_all.head()

,uuid,dem_education_level,dem_full_time_job,normalized_job_code,uuid.1,question_bbi_2016wave4_basicincome_awareness,question_bbi_2016wave4_basicincome_vote,question_bbi_2016wave4_basicincome_effect,question_bbi_2016wave4_basicincome_argumentsfor,question_bbi_2016wave4_basicincome_argumentsagainst,uuid.2,country_code,rural,uuid.3,age,gender,dem_has_children,age_group
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,NaN,f6e7ee00-deac-0133-4de8-0a81e8b09a82,I know something about it,I would not vote,None of the above,None of the above,None of the above,f6e7ee00-deac-0133-4de8-0a81e8b09a82,AT,countryside,f6e7ee00-deac-0133-4de8-0a81e8b09a82,61 years old,male,NO,40_65
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0,54f0f1c0-dda1-0133-a559-0a81e8b09a82,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,54f0f1c0-dda1-0133-a559-0a81e8b09a82,AT,urban,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57 years old,male,yES,40_65
2,83127080-da3d-0133-c74f-0a81e8b09a82,NaN,no,NaN,83127080-da3d-0133-c74f-0a81e8b09a82,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,83127080-da3d-0133-c74f-0a81e8b09a82,AT,city,83127080-da3d-0133-c74f-0a81e8b09a82,32 years old,male,nO,26_39
3,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,15626d40-db13-0133-ea5c-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above,15626d40-db13-0133-ea5c-0a81e8b09a82,AT,Country,15626d40-db13-0133-ea5c-0a81e8b09a82,45 years old,Male,YES,40_65
4,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,24954a70-db98-0133-4a64-0a81e8b09a82,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,24954a70-db98-0133-4a64-0a81e8b09a82,AT,city,24954a70-db98-0133-4a64-0a81e8b09a82,41 years old,Fem,yES,40_65

In [3]:
#Changing column names

new_names_list = ['uuid','education_level','full_time_job','job_code',
'uuid_1','quest_awareness',
'quest_vote',
'quest_effect',
'quest_arguments_for',
'quest_arguments_against',
'uuid_2',
'country_code',
'rural',
'uuid_3',
'age',
'gender',
'has_children',
'age_group']

df_all.columns = new_names_list


#filtering data needed

filter_list = ['uuid','education_level','full_time_job','job_code',
'quest_awareness',
'quest_vote',
'quest_effect',
'quest_arguments_for',
'quest_arguments_against',
'country_code',
'rural',
'age',
'gender',
'has_children',
'age_group']

df_all = df_all[filter_list]

In [4]:
df_all.head()

,uuid,education_level,full_time_job,job_code,quest_awareness,quest_vote,quest_effect,quest_arguments_for,quest_arguments_against,country_code,rural,age,gender,has_children,age_group
0,f6e7ee00-deac-0133-4de8-0a81e8b09a82,no,no,NaN,I know something about it,I would not vote,None of the above,None of the above,None of the above,AT,countryside,61 years old,male,NO,40_65
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,AT,urban,57 years old,male,yES,40_65
2,83127080-da3d-0133-c74f-0a81e8b09a82,NaN,no,NaN,I have heard just a little about it,I would not vote,‰Û_ gain additional skills,It creates more equality of opportunity,Foreigners might come to my country and take a...,AT,city,32 years old,male,nO,26_39
3,15626d40-db13-0133-ea5c-0a81e8b09a82,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,I have heard just a little about it,I would probably vote for it,‰Û_ work less,It reduces anxiety about financing basic needs,None of the above,AT,Country,45 years old,Male,YES,40_65
4,24954a70-db98-0133-4a64-0a81e8b09a82,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,AT,city,41 years old,Fem,yES,40_65

In [31]:
#Changing in education_level 

df_all['education_level'] = df_all['education_level'].fillna('undefined')
df_all['job_code'] = df_all['job_code'].fillna('undefined')

#function for remove strange characters
def replace(x):
    try:
        return x.replace("‰û_ ", "").replace("‰Û_ ", "")
    except:
        return x 
    
def lower(x):
    try:
        return x.lower()
    except:
        return x

In [6]:
df_all['quest_awareness'].value_counts()

I know something about it              3389
I understand it fully                  2389
I have heard just a little about it    2305
I have never heard of it               1566
Name: quest_awareness, dtype: int64

In [7]:
df_all['quest_vote'].value_counts()

I would probably vote for it        3272
I would vote for it                 2819
I would probably vote against it    1439
I would not vote                    1159
I would vote against it              960
Name: quest_vote, dtype: int64

In [8]:
df_all['quest_effect']= df_all['quest_effect'].apply(replace)

In [9]:
df_all['quest_effect'].value_counts()

A basic income would not affect my work choices    3349
spend more time with my family                     1387
None of the above                                  1227
gain additional skills                              970
look for a different job                            640
work less                                           629
do more volunteering work                           615
work as a freelancer                                465
stop working                                        367
Name: quest_effect, dtype: int64

In [10]:
#df_all['quest_arguments_for'].value_counts() --> Analyzing

In [11]:
#df_all['quest_arguments_against'].value_counts() --> Analyzing

In [12]:
df_all['country_code'].value_counts()

DE    1420
FR    1248
GB    1199
IT    1138
ES    1005
PL     860
RO     332
NL     331
GR     225
HU     206
PT     202
CZ     189
BE     179
SE     175
BG     141
AT     133
DK     119
FI     113
SK      93
IE      90
HR      87
LT      50
LV      36
SI      28
EE      18
CY      13
LU      11
MT       8
Name: country_code, dtype: int64

In [33]:
df_all['rural'] = df_all['rural'].apply(lower)
df_all['rural'].value_counts()

urban          3842
city           1664
rural          1517
non-rural      1372
country         772
countryside     482
Name: rural, dtype: int64

In [14]:
def replace_age(x):
    try:
        return int(x.replace(' years old',""))
    except:
        return x
    
df_all['age'] = df_all['age'].apply(replace_age) 

today = date.today().strftime("%d_%m_%y")

df_all['age'].value_counts()

Reference_age = '2016' #because from 1991 is in the age_group 25 and 1990 is in age 26 - CALCULATE THE AGE

40      477
45      402
41      400
42      342
43      338
44      297
1991    281
35      281
1989    257
46      257
47      249
1986    248
48      235
50      231
39      220
1987    220
49      210
1997    210
1990    207
1988    207
1996    202
31      196
1998    186
32      181
33      173
1994    169
51      167
34      165
53      160
38      160
52      159
1992    154
37      150
36      148
1993    148
1995    145
2000    133
55      132
54      126
2001    118
1999    116
59      107
57       93
58       91
56       83
2002     78
60       74
61       72
62       60
63       58
65       45
64       31
Name: age, dtype: int64

In [34]:
df_all['has_children'] = df_all['has_children'].apply(lower)
df_all['has_children'].value_counts()

yes    5049
no     4600
Name: has_children, dtype: int64

In [26]:
df_all['age_group'] = df_all['age_group'].replace("juvenile",'14_25')

df_all['age_group'].value_counts()

40_65    4896
26_39    2813
14_25    1940
Name: age_group, dtype: int64

In [18]:
#Export the detail analysis result to a CSV
path_to= '/home/usuario/Documentos/Ironhack/Project_1_0420_JuanMunoz/data/processed'
df_all.to_csv(f'{path_to}/clean_data_project.csv',index = False, header=True, sep = ';')